import Head from 'next/head'
import Navbar from '../src/components/Navbar'
import Hero from '../src/components/Hero'
import Domain from '../src/components/Domain'
import Achievements from '../src/components/Achivements'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main style={{minHeight: 100+'vh'}} className='flex flex-col justify-center items-center overflow-hidden'>
        <Hero />
        <Domain />
        <Achievements />
      </main>
    </>
  )
}
