name: Notifier

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  messageWhatsApp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Notification WhatsApp
        id: whatsapp-notify
        env:
          account_sid: ${{ secrets.WPP__TWILIO_ACCOUNT_SID }}
          auth_token: ${{ secrets.WPP__TWILIO_AUTH_TOKEN }}
          to_whatsapp_no: ${{ secrets.WPP_TWILIO_TO_WHATSAPP_NO }}
          message: "CI 👉🏻 Your message here"
        uses: khaled-ibtikar/whatsapp-push-notify-action@master